language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - nightly

env:
    matrix:
        - PREFER_LOWEST="--prefer-lowest"
        - PREFER_LOWEST=""

before_script:
    - composer update --prefer-source $PREFER_LOWEST
    - composer show
    - phpunit --version

script:
    - phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
